### ISSUE TITLE
makepasswd command not found

### ISSUE THREAD

**Issue by MrAmbiG** [newAM/unattended_ubuntu#1]
please use as generic in built commands as possible so that we don't have to spend more time in installing commands which are not found anywhere on internet than actually using this repo. After spending an hour or more I still can't find that makepasswd tool for ubuntu 18.

**Comment by newAM** [comment]
> After spending an hour or more I still can't find that makepasswd tool for ubuntu 18.

Something is wrong with your system.

The first result I get on google for "makepasswd ubuntu": https://packages.ubuntu.com/xenial/makepasswd

You can just install it with `sudo apt install makepasswd`

This works within Docker:
```
FROM ubuntu:18.04

RUN apt update
RUN apt install -y makepasswd
```

> please use as generic in built commands as possible so that we don't have to spend more time in installing commands which are not found anywhere on internet

I am happy to change this!  Do you have a better suggestion?
